### ISSUE TITLE
Pollution from local lua installation

### ISSUE THREAD

**Issue by NullCascade** [HolterPhylo/AMUMSS#13]
Currently, the locally installed lua environment will pollute the environment and prevent AMUNSS from running. This can be fixed by removing the `LUA_PATH` and `LUA_CPATH` environment variables since you are already using `SETLOCAL`. Without these changes, a conflicting version of e.g. lfs can cause AMUMSS to fail.

For example:
```bat
SETLOCAL EnableDelayedExpansion ENABLEEXTENSIONS

rem Prevent pollution from local lua installations.
set LUA_PATH=
set LUA_CPATH=
```

The following files seem to need the change:

- bzrun.bat
- MODBUILDER\Check_CONFLICTS.bat
- MODBUILDER\CreateMod.bat
- MODBUILDER\GetFreshSources.bat
- MODBUILDER\MBINCompilerDownloader.bat

I'm not sure of the structure of this project. It has a lot of duplicate files and version history built-in? I'm not sure how to appropriately submit a PR for how you want things managed, but hopefully the above information helps for a future update.

**Comment by HolterPhylo** [comment]
Please explain how LUA_PATH and LUA_CPATH are preventing AMUMSS from running!
No where in the code these two variables are used...

**Comment by NullCascade** [comment]
`LUA_PATH` and `LUA_CPATH` are not AMUMSS-specific, they are used by lua itself. You can read more about it in the [Lua Manual, Chapter 8.1](https://www.lua.org/pil/8.1.html).

As an alternative, you can probably overwrite this behavior by changing every lua file by configuring `package.path` and `package.cpath`. Though since you're pushing/popping the environment with `SETLOCAL` already, and have a fair few lua files, the original suggestion is the easiest.

**Comment by HolterPhylo** [comment]
> Currently, the locally installed lua environment will pollute the environment and prevent AMUNSS from running. This can be fixed by removing the `LUA_PATH` and `LUA_CPATH` environment variables since you are already using `SETLOCAL`. Without these changes, a conflicting version of e.g. lfs can cause AMUMSS to fail.
> 
> For example:
> 
> ```batchfile
> SETLOCAL EnableDelayedExpansion ENABLEEXTENSIONS
> 
> rem Prevent pollution from local lua installations.
> set LUA_PATH=
> set LUA_CPATH=
> ```
> 
> The following files seem to need the change:
> 
> * bzrun.bat
> * MODBUILDER\Check_CONFLICTS.bat
> * MODBUILDER\CreateMod.bat
> * MODBUILDER\GetFreshSources.bat
> * MODBUILDER\MBINCompilerDownloader.bat
> 
> I'm not sure of the structure of this project. It has a lot of duplicate files and version history built-in? I'm not sure how to appropriately submit a PR for how you want things managed, but hopefully the above information helps for a future update.

Specifically this statement:
> the locally installed lua environment will pollute the environment and prevent AMUNSS from running.

Could you please explain why/how this prevents AMUMSS from running its custom lua.exe?  What are you seeing in the cmd window when executing BUILDMOD.bat?
Please provide log or screenshot of problem you are seeing when trying to run AMUMSS

**Comment by HolterPhylo** [comment]
Issue will be Closed after 7 days from now, due to lack of feedback

**Comment by HolterPhylo** [comment]
Close for lack of feedback...
