### ISSUE TITLE
.net5 DESKTOP runtime x64 is missing, but I installed it

### ISSUE THREAD

**Issue by just-ads** [HolterPhylo/AMUMSS#16]
![image](https://github.com/HolterPhylo/AMUMSS/assets/50706050/c0a74100-ca95-4eee-b23d-def1b25899d2)

**Comment by HolterPhylo** [comment]
Please go to Discord as specified at the bottom of the README.  Easier and faster help that way.
![image](https://github.com/HolterPhylo/AMUMSS/assets/3037251/8548d34d-1f06-4a1c-9ad8-cc9cb3d7bf03)

**Comment by HolterPhylo** [comment]
user joined Discord as requested
