### ISSUE TITLE
AMUMSS not detecting .NET 5

### ISSUE THREAD

**Issue by Alexyoe** [HolterPhylo/AMUMSS#17]
I've installed .NET 5 via BUILDMOD.bat and from the Microsoft website but when I run BUILDMOD.bat it asks to install it again every time.

**Comment by Babscoole** [comment]
Not sure exactly what you've installed as MS has several different flavors on the .net 5 landing page, including the SDK.  Can be confusing.  Direct link to the correct installer (assuming your system is x64) is https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer.  May also want to do a reboot after the install.

**Comment by Babscoole** [comment]
Do you have Discord?  Come to the NMS Modding server at https://discord.gg/VZVU7rD4D5.  #amumss-lua channel.  Can get you fixed up in real time

**Comment by Alexyoe** [comment]
Thanks for the reply! Unfortunately, none of these steps seem to fix the issue. I went ahead and posted in the discord chat. Once the issue is resolved I'll post on this issue what steps were taken to resolve the issue and close it.

**Comment by Babscoole** [comment]
Yeah see you and Wbertros got you

**Comment by Alexyoe** [comment]
Issue resolved with a modified bzrun.bat.
