### ISSUE TITLE
Windows CodeIntegrity blocks wtee.exe 

### ISSUE THREAD

**Issue by Yousei9** [HolterPhylo/AMUMSS#22]
With the [MS hotfix to block vulnerable drivers](https://learn.microsoft.com/en-us/windows/security/threat-protection/windows-defender-application-control/microsoft-recommended-driver-block-rules) installed parts of AMUMSS also get blocked.

```
CodeIntegrity EventID 3033:

Code Integrity determined that a process (\Device\HarddiskVolume5\Windows\SysWOW64\cmd.exe) attempted to load \Device\HarddiskVolume1\AMUMSS\MODBUILDER\wtee.exe that did not meet the Unchecked signing level requirements.
```

**Comment by Babscoole** [comment]
wtee is a freely available port of the unix command tee for windows that's been around for years.  If the author(s) wish to take this up with MS, they are welcome to, but as an end user of the software, the AMUMSS author really doesn't have the authority to do so.

In all documentation for AMUMSS, it is recommended to create an exception/exclusion/bypass for the entire AMUMSS directory, as much of it relies upon command line tool and batch files, which are prone to be blocked by poorly designed security solutions.

**Comment by Yousei9** [comment]
After multiple restarts wtee.exe is no longer blocked even without defender exclusion.
