### ISSUE TITLE
BUILDMOD.BAT stuck after updating path to NMS

### ISSUE THREAD

**Issue by Inny78** [HolterPhylo/AMUMSS#26]
After successfully updating the path in NMS_FOLDER.txt, the script is stuck.
Here's the log:

  01/04/2024  1:22:07,58 AMUMSS starting!

 [38;2;242;242;242m[48;2;0;128;128m >>> Note: Please make sure no [0m[7m 'accented characters' [0m[38;2;242;242;242m[48;2;0;128;128m are in AMUMSS path [0m

[38;2;22;198;12m  AMUMSS v4.3.4.1W[0m
[38;2;22;198;12m  BUILDMOD v1.9.3 (64)[0m
[38;2;22;198;12m  Lua 5.4.4 custom version with lfs[0m
[38;2;22;198;12m  Windows 11 Pro 64bit, Build: 22631.3296 with 20 logical CPUs (cp850)[0m
[38;2;22;198;12m    .NET 5 Desktop Runtime exist[0m
[38;2;22;198;12m    .NET 6 Desktop Runtime exist[0m
  [38;2;22;198;12m===> NMS version 120200[0m

>>>  Starting in D:\Down\Mods\NMS\AMUMSS

>>>  Checking Path to NMS_FOLDER...

 [38;2;12;12;12m[48;2;255;255;102m Path to NMS_FOLDER is >>>[0m[38;2;242;242;242m[48;2;0;128;128m GOOD [0m[38;2;12;12;12m[48;2;255;255;102m<<< game files found [0m

>>>  Updating CONFIG\NMS_FOLDER.txt to "D:\Jeux\Steam\steamapps\common\No Man's Sky"

**Comment by HolterPhylo** [comment]
It is impossible to help you here, that would take days with you and me exchanging information at a snail pace...

The bottom part of the Readme on the main page says

![image](https://github.com/HolterPhylo/AMUMSS/assets/3037251/519d7be3-6a15-4b0d-a799-eaa818f881e3)

That is what you have to do for help!

Closing this.
