### ISSUE TITLE
PAK files are no longer being created.

### ISSUE THREAD

**Issue by ThePenitence** [HolterPhylo/AMUMSS#3]
My AMUMSS is no longer creating PAK files upon completion of compiling using BUILDMOD.bat. It goes through the process as normal and shows values being changed as instructed by LUA scripts provided but it doesn't create any PAK files. It does however create the pak_content.txt file that is created when combining scripts. This is my first time using it in a couple of months and updated it with the latest version found here.

**Comment by HolterPhylo** [comment]
is mbincompiler showing that it is compiling?  mbincompiler requires .net5
now.
Did you see a message to that effect?  If so follow the instructions.

Or your anti-virus program may be blocking parts of it?  Create an
exception for the whole AMUMSS folder

If not any of that, send me the log.txt file and I’ll look into it

**Comment by HolterPhylo** [comment]
This was resolved for you?
