### ISSUE TITLE
Tasklist

### ISSUE THREAD

**Issue by SVG1** [HolterPhylo/AMUMSS#32]
Please tell me why AMUMSS launches the file "Tasklist.exe"? Why does she need a list of processes? All this looks too suspicious...

**Comment by HolterPhylo** [comment]
Did you inspect the code lines where Tasklist.exe is used?
Everything line where TaskList is used can be inspected in any text editor.
If you did you would know why it is used...

If you need more information after that, please ask

**Comment by SVG1** [comment]
Sorry, I'm not good at coding. Through the firewall I found that "tasklist.exe" was running.

**Comment by HolterPhylo** [comment]
Please do not call something 'suspicious' without investigating first.

tasklist.exe is called in 2 .lua scripts in a very targeted way both times:

- In CreateMapFileTree.lua: to check if the main .lua script (LoadAndExecuteModScript.lua) is still running.  Code is `tasklist /FI "ImageName eq lua.exe"`
- In LoadAndExecuteModScript.lua: to check if the above CreateMapFileTree.lua script is already running or not (to prevent starting a new one).  Code is `tasklist /FI "ImageName eq luaM.exe"`

Two legitimate uses.

Hope that helps!

**Comment by SVG1** [comment]
Thanks for the clarification, I have no more questions. I'm sorry to trouble you.
