### ISSUE TITLE
Creating a Lua file from exml.

### ISSUE THREAD

**Issue by SVG1** [HolterPhylo/AMUMSS#33]
Can AMUMSS automatically create a lua file from .exml or mbin files? If not, could you add this feature?
For example: in one folder intended for original files you put the original file from the game, and in another folder you put a file with the same name but modified. AMUMSS compares these files and creates a lua file based on the differences. Is it possible to do this?

**Comment by HolterPhylo** [comment]
In modding we always work with exml files which are basically text files.
It would be possible for 'very' simple changes to an exml file, like value changes to automate the process of creating a script.
There is no compare tool that can, at the moment, be used to compare two exml files when more complex changes are made.
It is probably possible to create such A) a compare tool but then that would push the problem to B) devise a way to write a script that would replicate that, another piece of code.
That is two tools to create.
But, again, that would only cover 'very' simple changes.  Not very useful compared to writing a script which can be done in a few minutes using an example or from a template for those types of changes.

Considering the amount of work involved to create A) and B) compared to writing a script, it is very low on my list of things to code.
I hope that answer your question.

**Comment by SVG1** [comment]
Yeah thanks ! 
Looks like I'll have to come to terms with it :(
