### ISSUE TITLE
did these insane filenames break psarc?

### ISSUE THREAD

**Issue by darkconsole** [HolterPhylo/AMUMSS#35]
![image](https://github.com/user-attachments/assets/e966cbc9-50d8-46ee-b793-d14aacea7500)

not sure why it cant just be ~merged.pak (or whatnot) at some point ntfs is going to lose its mind over this.

**Comment by HolterPhylo** [comment]
1) QUESTIONS * Questions are better asked in NMS Discord: "No Man's Sky Modding" channel, "amumss-lua" room: https://discord.gg/HFjnmnwe67
We have channel #amumss-lua dedicated to AMUMSS/NMSPE with helpful modders and Wbertro#8596 (aka TheBossBoy)

2) FOR HELP WITH INSTALLATION: Refer to https://www.nexusmods.com/nomanssky/mods/2626

3) Always read the README, it is there for a reason.

That being said:
Follow the INSTALLATION guidelines and that should resolve your problems.  NEVER install in the game folders!!

Wbertro
