### ISSUE TITLE
Replacing wrong value in EXML using PRECEDING_KEY_WORDS as a search method, find result before PRECEDING_KEY_WORDS not after

### ISSUE THREAD

**Issue by Smugger21** [HolterPhylo/AMUMSS#5]
In your ModScriptCollection you have a Demo Script called "UnlimitedHyperDriveDistance_UnlimitedJetPack_ZeroLaunchCost"
[ I have tested this extensively even with another person LUA from the nexus with the same result (Nexus Link: https://www.nexusmods.com/nomanssky/mods/918 ) ]

Code Part Causing the issue:
```
						{
							["SPECIAL_KEY_WORDS"] = {"ID","HYPERDRIVE",},
							["PRECEDING_KEY_WORDS"] = {"Ship_Hyperdrive_JumpDistance",},
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Bonus",	"9000000"}, 	-- Original "100"
							}
						},
```

Result:
NMS_REALITY_GCTECHNOLOGYTABLE.EXML
Lines: 3912 - 3934
```
      <Property name="StatBonuses">
        <Property value="GcStatsBonus.xml">
          <Property name="StatsTypes" value="GcStatsTypes.xml">
            <Property name="StatsType" value="Ship_Hyperdrive" />
          </Property>
          <Property name="Bonus" value="9000000" />
          <Property name="Level" value="1" />
        </Property>
        <Property value="GcStatsBonus.xml">
          <Property name="StatsTypes" value="GcStatsTypes.xml">
            <Property name="StatsType" value="Ship_Hyperdrive_JumpDistance" />
          </Property>
          <Property name="Bonus" value="100" />
          <Property name="Level" value="1" />
        </Property>
        <Property value="GcStatsBonus.xml">
          <Property name="StatsTypes" value="GcStatsTypes.xml">
            <Property name="StatsType" value="Ship_Hyperdrive_JumpsPerCell" />
          </Property>
          <Property name="Bonus" value="1" />
          <Property name="Level" value="1" />
        </Property>
      </Property>
```

Expected Result:
```
      <Property name="StatBonuses">
        <Property value="GcStatsBonus.xml">
          <Property name="StatsTypes" value="GcStatsTypes.xml">
            <Property name="StatsType" value="Ship_Hyperdrive" />
          </Property>
          <Property name="Bonus" value="1" />
          <Property name="Level" value="1" />
        </Property>
        <Property value="GcStatsBonus.xml">
          <Property name="StatsTypes" value="GcStatsTypes.xml">
            <Property name="StatsType" value="Ship_Hyperdrive_JumpDistance" />
          </Property>
          <Property name="Bonus" value="9000000" />
          <Property name="Level" value="1" />
        </Property>
        <Property value="GcStatsBonus.xml">
          <Property name="StatsTypes" value="GcStatsTypes.xml">
            <Property name="StatsType" value="Ship_Hyperdrive_JumpsPerCell" />
          </Property>
          <Property name="Bonus" value="1" />
          <Property name="Level" value="1" />
        </Property>
      </Property>
```

Changing the LUA to use this will make it get the desired effect:
```
						{
							["SPECIAL_KEY_WORDS"] = {"ID","HYPERDRIVE",},
							["PRECEDING_KEY_WORDS"] = {"Ship_Hyperdrive_JumpDistance",},
                                                        ["VALUE_MATCH"] = "100",
							["VALUE_CHANGE_TABLE"] 	= 
							{
								{"Bonus",	"9000000"}, 	-- Original "100"
							}
						},
```

Even though I was able to do it using that, I assume since your own Demo Script Collection has the first code, it is not supposed to be doing that.

This is easy to duplicate this result by using the Unmodified version of the "UnlimitedHyperDriveDistance_UnlimitedJetPack_ZeroLaunchCost" file in the ModScriptCollection and extracting the PAK and then extracting the NMS_REALITY_GCTECHNOLOGYTABLE.MBIN under METADATA\REALITY\TABLES

**Comment by HolterPhylo** [comment]
> This is easy to duplicate this result by using the Unmodified version of the "UnlimitedHyperDriveDistance_UnlimitedJetPack_ZeroLaunchCost" file in the ModScriptCollection and extracting the PAK and then extracting the NMS_REALITY_GCTECHNOLOGYTABLE.MBIN under METADATA\REALITY\TABLES

For info, you know you can always find (for the last script processed) all the MODDED EXMLs in the folder EXML_Helper\MODDED with the ORIGINALs in EXML_Helper\ORG_EXML folder.  No need to do the "extracting / decompiling" yourself.

**Comment by HolterPhylo** [comment]
And putting any pak(s) in ModScript, without any script in the folder, will unpak / decompile it/them and save the results in a folder named for each pak in folder UNPACKED_DECOMPILED_PAKs.

And by any pak, I mean any.  PCBANKS or modded pak.

You can even put MBINs in there and they will be decompiled...

**Comment by HolterPhylo** [comment]
Done

**Comment by HolterPhylo** [comment]
Done in v.3.9.3W
