### ISSUE TITLE
AMUMSS 3.9.5.8W - Included curl.exe incompatible with Windows 7

### ISSUE THREAD

**Issue by MrSmite** [HolterPhylo/AMUMSS#7]
**OS:** Win 7 Pro x64

**Bug:** The included curl.exe is incompatible with Windows 7

**Detail:**

I have updated a few mods for the 3.71 version of NMS using AMUMSS 3.9.5W. Today when I ran BUILDMOD, it indicated there was a new version available so I allowed it to update to 3.9.5.8W. After the update was finished, I started getting the following error from CURL.exe:

_api-ms-win-core-processenvironment-l1-2-0.dll is missing_

This dll is part of Windows 10 and the only place I can find a download for windows 7 are random DLL download sites that I don't trust to install runtimes from.

**Temporary Solution:**

I ended up copying the _MBINCompilerDownloader_ folder from an older amumss version: 3.9.5W to get a _curl.exe_ version that works on Win 7.

**Comment by HolterPhylo** [comment]
Sorry about that, I reverted to previous version in 3.9.5.10W

**Comment by MrSmite** [comment]
> Sorry about that, I reverted to previous version in 3.9.5.91W, now live

No problem, thanks for the quick attention.
