### ISSUE TITLE
net core bug?

### ISSUE THREAD

**Issue by Baddtraxx** [HolterPhylo/AMUMSS#8]
I had .net 3.4 before, amumss said it needs 5.0, so I updated and have 6.0, so an even further branch, since 5.0 is no longer supported. and I still get errors.

**Comment by HolterPhylo** [comment]
Sorry for the trouble!

AMUMSS uses MBINCompiler.exe AND MBINCompiler.exe REQUIRES '.NET 5 x64 Desktop Runtime' latest version to run.

It can be found at [https://dotnet.microsoft.com/download/dotnet/5.0/runtime](https://dotnet.microsoft.com/download/dotnet/5.0/runtime) 

Even if .NET 5 is technically at 'end of life', that is what is required for now and .NET 6 is NOT backward compatible with .NET 5

I updated the README to reflect this
